config/routes.rb
PCOI::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  resources :jobs, only: [:index, :show]
  resources :sectors, only: [:show]

  namespace :api do
    resources :jobs, only: [:index]
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :region
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :country
  belongs_to :sector

  def self.filter(sector, region)
    return all.order(:need) if sector.nil? && region.nil?

    sector_jobs = sector.jobs if sector
    return sector_jobs.sort { |job1, job2| job1.need <=> job2.need } if sector && region.nil?

    region_jobs = region.jobs if region
    return region.jobs.sort { |job1, job2| job1.need <=> job2.need } if region && sector.nil?

    sector_and_region_jobs = (sector_jobs + region_jobs)
    sector_and_region_jobs.select{ |job| sector_and_region_jobs.count(job) > 1 }.sort { |job1, job2| job1.need <=> job2.need }
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :countries

  def jobs
    self.countries.map { |country| country.jobs }.flatten
  end
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  has_many :jobs
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
  respond_to :json

  def index
    respond_with Job.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @filtered_jobs = Job.filter(Sector.find_by(id: params[:sector_id]), Region.find_by(id: params[:region_id]))
  end

  def show
    @job = Job.find(params[:id])
    render :layout => false
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  def show
    @sector = Sector.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @regions = Region.all
    @sectors = Sector.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def prettify_date(date_time)
    Date.parse(date_time.split.first).strftime('%a %d %b %Y')
  end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_jobs.html.erb
<tr class="head">
	<th>Need</th>
	<th>Job Title</th>
	<th>Country</th>
	<th>Departure Date</th>
	<th></th>
</tr>
<% filtered_jobs.each do |job| %>
  <tr>
    <td><%= "#{job.need}" %></td>
    <td class="job_title"><%= "#{job.title}" %></td>
    <td><%= "#{job.country.try(:name) || "n/a"}" %></td>
    <td class="departure_date"><%= "#{prettify_date(job.departure_date)}" %></td>
    <td><button class="actions btn btn-primary" data-toggle="modal" data-target="#myModal" data-id="<%= job.id %>">View Details and Apply</button></td>
    <!--<td><button class="actions btn btn-primary" data-id="<%= job.id %>">View Details and Apply</button></td>-->
  </tr>
<% end %>

app/views/jobs/index.js.erb
$('#search-results').html('<%= j render "jobs", filtered_jobs: @filtered_jobs %>')

app/views/jobs/show.html.erb
<div class='container job_show'>
      <a name="top"></a> 
      <div class='row job_description'>
            <h2><%= @job.title %> in <%= @job.country.name %></h2>
            <div class=' row need'><div class='col-md-6'><span class="glyphicon glyphicon-asterisk"></span>High Need</div></div>
            <iframe width="100%" height="285" src="//www.youtube.com/embed/jM8y9jJXNJw" frameborder="0" allowfullscreen></iframe>
            <a name="summary"></a> 
      </div>
      <div class='row navigation'>
            <div class="btn-group">
                    <a class='to_top' href='#quick_info'>Quick Info</a>
                    <a class='to_top' href='#summary'>Summary</a>
                    <a class='to_top' href='#skills'>Desired Skills</a>
                    <a class='to_top' href='#physical_requirements'>Physical Requirements</a>
            </div>
      </div>
      <div class='row job_quick_info'>
            <a name="quick_info"></a> 
            <h3>Quick Info</h3>
            <div class='col-md-6'>
                  <div class='row open_positions'>
                        <div class='col-md-6'><span class='label'>Positions Open: </span></div>
                        <div class = 'col-md-6'><%= @job.open_positions %></div>
                  </div>
                  <div class='row'>
                        <div class='col-md-6'><span class='label'>Application Deadline: </span></div>
                        <div class = 'col-md-6'>M, 10/24/13</div>
                  </div>
                  <div class='row'>
                        <div class='col-md-6'><span class='label'>Notification Deadline: </span></div>
                        <div class = 'col-md-6'>W, 1/13/14</div>
                  </div>
                  <div class='row'>
                        <div class='col-md-6'><span class='label'>Departure Date: </span></div>
                        <div class = 'col-md-6'>Th, 6/27/14</div>
                  </div>
                  <div class='row bookmark'>
                        <div class='col-md-6'>
                              <button type="button" class="btn btn-default btn-lg">
                                    <span class="glyphicon glyphicon-bookmark"></span> Bookmark This Job
                              </button>
                              <p><a href='#top'>Back To Top</a></p>
                        </div>
                  </div>
            </div>
            <div class='col-md-6 job_profile_pic'>
                  <%= image_tag('jobs_show_01.jpg') %>
            </div>
      </div>
      <div class='row'>
            <a name="summary"></a> 
            <h3>Summary</h3>
            <p><%= @job.description %></p>
            <p><a href='#top'>Back To Top</a></p>
      </div>
      <div class='row desired skills'>
            <a name="skills"></a> 
            <h3>Desired Skills</h3>
            <p><%= @job.skills %></p>
            <p><a href='#top'>Back To Top</a></p>
      </div>
      <div class='row job_physical'>
            <a name="physical_requirements"></a> 
            <h3>Physical Requirements</h3>
            <p><%= @job.physical_requirements %></p>
            <p><a href='#top'>Back To Top</a></p>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>PCOI - Find Your Corps</title>

  <!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>-->
  <%= javascript_include_tag 'http://maps.google.com/maps/api/js?v=3&sensor=false' %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- Twitter Bootstrap -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sectors/_own_words.html.erb
<h2>In Their Own Words</h2>
<div class = 'col-md-6'>
	<h3>Volunteer Blogs</h3>
	<div class='row-fluid'>
		<div class='col-md-6'>
			<ul>
				<li><%= link_to 'Simply Intentional', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'The Gambia', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'Namibia', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'There By The Shore', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'What I Learned In The PC', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'Meg Wandering', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'Taste Of Peace', 'http://simplyintentional.wordpress.com/
		' %></li>
			</ul>
		</div>
		<div class='col-md-6'>
			<ul>
				<li><%= link_to 'Jen and Joshn in Ethiopia', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'PC Guinea', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'To Guatemala', 'http://simplyintentional.wordpress.com/
		' %></li>
				<li><%= link_to 'Traditional', 'http://simplyintentional.wordpress.com/
		' %></li>
			</ul>
		</div>
	</div>

</div>
<div class = 'col-md-6'>
	<h3>Volunteer Stories</h3>
	<h4><%=link_to 'From Hawaii to Benin', '#' %></h4>
	<p class='story'>
		Peace Corps was the ultimate cross-cultural experience. Learning new cultures was really my main goal. I didn't go in with arrogant ideas of saving native villagers from themselves by teaching them the American way of doing things. I wanted to learn and experience what they could teach me. When I was posted in a small bush village in Benin, I was thrilled thinking that I got exactly what I wanted-a remote place with optimal opportunity for cultural immersion.
	</p>
	<p class= 'volunteer pull-right'>
		<%=link_to 'Dana Miller', '#' %>, Benin
	</p>
</div>

app/views/sectors/_sector_carousel.html.erb
 <div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%=image_tag('sector_01.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Helping</h1>
          <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
    <div class="item">
      <%=image_tag('sector_02.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Making an Impact</h1>
          <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
    <div class="item">
      <%=image_tag('sector_03.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Empower Others</h1>
          <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/sectors/_story_carousel.html.erb
 <div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <div class="container">
        <div class="carousel-caption">
          <h1><%=link_to 'From Hawaii to Benin', '#' %></h1>
          <p class='story'>
            Peace Corps was the ultimate cross-cultural experience. Learning new cultures was really my main goal. I didn't go in with arrogant ideas of saving native villagers from themselves by teaching them the American way of doing things. I wanted to learn and experience what they could teach me. When I was posted in a small bush village in Benin, I was thrilled thinking that I got exactly what I wanted-a remote place with optimal opportunity for cultural immersion.
        </p>
        <p><%=link_to 'Dana Miller', '#' %>, Benin</p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="carousel-caption">
          <h1><%=link_to 'If Theres Enough For One', '#' %></h1>
          <p class='story'>
            Then it came unbidden into my mind: If there’s enough for one, there’s enough for two. Suddenly, all the sayings and traditions around food that I had been observing coalesced into something large enough to spur change. I was able to push it all aside: my embarrassment at the meager portions, my worry that he would think it tasted bad, my self-ishness at the thought of biking so far on such little nourishment. What matters is that someone who might not eat all day has something to put in his stomach, I finally realized. And what matters is a willingness to share, ungrudgingly and without hesitation.
          </p>
          <p><%=link_to 'Kara Garbe', '#' %>, Burkina Faso </p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="carousel-caption">
          <h1><%=link_to 'Family Affair', '#' %></h1>
          <p class='story'>
            Seeing how these former students reacted to my parents was incredible, persuasive evidence that Peace Corps Volunteers have a profound influence wherever they go, whatever they do. In fact, I felt that a Volunteer could almost spend the entire two years of service locked inside a house and still change something significant in the lives of people all around.
          </p>
          <p><%=link_to 'Tana Beverwyk', '#' %>, Malawi</p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/sectors/show.html.erb
<div class='container sector_show'>
	<div class='row'>
		<%= render 'sector_carousel', :sector => @sector%>
	</div>
	<div class="container">
		<div class='row sector_description'>
			<h1><%= @sector.name.titleize %></h1>
			<div class='col-md-8'>
				<p class='lead'>This is the largest area of need for Peace Corps countries. Education Volunteers team-teach or directly teach English, health, literacy, math, and science. Education Volunteers strengthen local capacity by training and mentoring teachers in primary and secondary schools, teacher training colleges, and universities. Volunteers work with teachers to improve participatory teaching methodologies, inclusion practices, classroom management, authentic assessments, parental involvement, and gender equality in the classroom. They also create after-school programs, clubs, and camps for boys and girls to promote HIV/AIDS prevention and life skills.</p>
			</div>
			<div class='col-md-4'>
				<iframe width="100%" height="285" src="//www.youtube.com/embed/8uRbeW-Vro8" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div class='row own_words'>
			<%= render 'own_words' %>
		</div>
		<div class='row'>
			<%= link_to "All #{@sector.name.titleize} Opportunities >>", '#', class: 'pull-right btn' %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div id="wrapper">
    <header id="nav">
	    <button type="button" id="show-menu" class="btn btn-default btn inline">
	  		<span class="glyphicon glyphicon-align-justify left"></span>
		</button>
		<ul id="top-menu">
			<% @sectors.each do |sector| %>
  		        <li><%= link_to sector.name.titleize.split.first, sector_path(sector) %> </li>
            <% end %>
		</ul>
    </header>
    <div id="filterdiv">
         <form id="interests" name="setInterests" class="inline" action='/jobs' method="get">
         	<p class="inline">I'm interested in</p>
           	<div class="check-selections inline" id="sectors-container">
           		<select id="sectors" class="form-control">
           			<option value='0'>All Sectors</option>
  		            <% @sectors.each do |sector| %>
  		            	<option value='<%= sector.id %>'><%= sector.name.titleize %></label></option>
  		            <% end %>
  		        </select>
  	        </div>


			<p class="inline">in</p>
			<div class="check-selections inline small" id="regions-container">
				<select id="regions" class="form-control">
					<option value='0'>All Regions</option>
		            <% @regions.each do |region| %>
		            	<option value='<%= region.id %>'><%= region.name.titleize %></option>
                <% end %>
		        </select>
	        </div>
	        <div class="form-horizontal">
         		<button type="submit" class="submit btn btn-success btn-lg" value="Find Opportunities">Find Opportunities</button>
         		<!--
         		<p class="inline"> or </p>
         		<button class="btn btn-default btn-sm" value="Get A Suggestion">Get A Suggestion</button>
         		-->
         	</div>
         </form>
    </div>
    <div id="map-canvas"></div>
    <div>
    	<table id="search-results" class="med">

		</table>
	</div>
	<!-- Job Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	      	<div class="spacer">
	        	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        </div>
	        <!--<h4 class="modal-title" id="myModalLabel"></h4>-->
	      </div>
	      <div class="modal-body">
	      </div>

	      <div class="modal-footer">
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style addthis_32x32_style col-md-10 col-md-offset-2">
			  <a class="addthis_button_preferred_1"></a>
			  <a class="addthis_button_preferred_2"></a>
			  <a class="addthis_button_preferred_3"></a>
			  <a class="addthis_button_preferred_4"></a>
			  <a class="addthis_button_compact"></a>
			  <a class="addthis_counter addthis_bubble_style"></a>
			</div>
			<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51febb8b0c7aa2c1"></script>
			<!-- AddThis Button END -->

			<button type="button" class="btn btn-primary">Apply Now!</button>

	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->